name: Build Mod

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build the mod
        uses: geode-sdk/build-geode-mod@main
        with:
          sdk: nightly
          combine: true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dim5lBOT
          path: ${{ github.workspace }}/build/*.geode

      - name: Auto Release
        uses: marvinpinto/action-automatic-releases@latest
        if: github.ref == 'refs/heads/main'
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "dim5lBOT Latest Build"
          files: ${{ github.workspace }}/build/*.geode
